const currentYear = new Date().getFullYear()

const sharedSupplier = {
    name: 'Northline Studio s.r.o.',
    ico: '28984561',
    vat: 'CZ28984561',
    address: 'Sokolovska 128/44, Karlin, 186 00 Praha 8',
    registry:
        'Spolecnost je zapsana v obchodnim rejstriku vedenem Mestskym soudem v Praze, spisova znacka C 158421.',
    phone: '+420 777 441 218',
    email: 'hello@northline.studio',
    website: 'northline.studio',
}

export const createMockInvoices = () => [
    {
        id: 'demo-invoice-1',
        invoiceNumber: `${currentYear}001`,
        issueDate: `${currentYear}-04-03`,
        dueDate: `${currentYear}-04-17`,
        taxableSupplyDate: `${currentYear}-04-03`,
        status: 'paid',
        category: 'Brand Design',
        client: {
            name: 'Atelier Vltava',
            email: 'finance@ateliervltava.cz',
            emailCopy: 'owner@ateliervltava.cz',
            phone: '+420 603 220 995',
            area: 'Prague',
            ico: '27451032',
            vat: 'CZ27451032',
            address: 'Masarykovo nabrezi 24, 110 00 Praha 1',
        },
        items: [
            {
                name: 'Brand workshop and positioning',
                qty: 1,
                price: 18000,
                taxRate: 21,
                discount: 0,
                total: 18000,
            },
            {
                name: 'Visual identity system',
                qty: 1,
                price: 29500,
                taxRate: 21,
                discount: 0,
                total: 29500,
            },
        ],
        currency: 'CZK',
        amount: 57475,
        payment: {
            iban: 'CZ6508000000192000145399',
            bic: 'GIBACZPX',
            note: 'Design retainer - spring launch',
            accountNumber: '192000145399',
            bankCode: '0800',
            variableSymbol: `${currentYear}001`,
        },
        supplier: sharedSupplier,
        isVatPayer: true,
        taxBase: '47500.00',
        taxRate: '21',
        taxAmount: '9975.00',
    },
    {
        id: 'demo-invoice-2',
        invoiceNumber: `${currentYear}002`,
        issueDate: `${currentYear}-04-10`,
        dueDate: `${currentYear}-04-24`,
        taxableSupplyDate: `${currentYear}-04-10`,
        status: 'sent',
        category: 'Product UX',
        client: {
            name: 'Luma Health Labs',
            email: 'ops@lumahealth.io',
            emailCopy: '',
            phone: '+49 30 251 922 00',
            area: 'Berlin',
            ico: 'DE309118220',
            vat: 'DE309118220',
            address: 'Prenzlauer Allee 210, 10405 Berlin',
        },
        items: [
            {
                name: 'Mobile onboarding redesign',
                qty: 1,
                price: 24000,
                taxRate: 21,
                discount: 1500,
                total: 22500,
            },
            {
                name: 'Prototype testing summary',
                qty: 1,
                price: 8500,
                taxRate: 21,
                discount: 0,
                total: 8500,
            },
        ],
        currency: 'CZK',
        amount: 37510,
        payment: {
            iban: 'CZ6508000000192000145399',
            bic: 'GIBACZPX',
            note: 'Sprint 4 UX delivery',
            accountNumber: '192000145399',
            bankCode: '0800',
            variableSymbol: `${currentYear}002`,
        },
        supplier: sharedSupplier,
        isVatPayer: true,
        taxBase: '31000.00',
        taxRate: '21',
        taxAmount: '6510.00',
    },
    {
        id: 'demo-invoice-3',
        invoiceNumber: `${currentYear}003`,
        issueDate: `${currentYear}-03-26`,
        dueDate: `${currentYear}-04-02`,
        taxableSupplyDate: `${currentYear}-03-26`,
        status: 'overdue',
        category: 'Strategy',
        client: {
            name: 'Nord Harbor Retail',
            email: 'accounting@nordharbor.com',
            emailCopy: '',
            phone: '+45 88 44 19 20',
            area: 'Copenhagen',
            ico: 'DK41209975',
            vat: 'DK41209975',
            address: 'Nyhavn 12, 1051 Copenhagen K',
        },
        items: [
            {
                name: 'Quarterly growth audit',
                qty: 1,
                price: 12600,
                taxRate: 21,
                discount: 0,
                total: 12600,
            },
            {
                name: 'Executive roadmap deck',
                qty: 1,
                price: 6400,
                taxRate: 21,
                discount: 0,
                total: 6400,
            },
        ],
        currency: 'CZK',
        amount: 22990,
        payment: {
            iban: 'CZ6508000000192000145399',
            bic: 'GIBACZPX',
            note: 'Q2 strategy package',
            accountNumber: '192000145399',
            bankCode: '0800',
            variableSymbol: `${currentYear}003`,
        },
        supplier: sharedSupplier,
        isVatPayer: true,
        taxBase: '19000.00',
        taxRate: '21',
        taxAmount: '3990.00',
    },
]